name: PR
on:
  pull_request:
    branches:
      - main
      - release-*
    paths-ignore:
      - "**.md"
      - "docs/**"
      - "**.txt"
      - "images/**"
      - "LICENSE"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
